### ISSUE TITLE
Hang when closing a large json file

### ISSUE THREAD

**Issue by naseer** [neoclide/coc-highlight#10]
I was editing a large `compile_commands.json` file and noticed that highlight caused a hang when exiting. Disabling this extension fixed it.

**Comment by chemzqm** [comment]
Please provide the way to reproduce.

**Comment by naseer** [comment]
Unable to share the compile commands, but
1. Open any large compile commands json (like Linux kernel)
2. Search for some location
3. Close neovim

**Comment by chemzqm** [comment]
Should be fixed on version 2.0.0 which using work threads.
