### ISSUE TITLE
Intelligent text coloring

### ISSUE THREAD

**Issue by SicariusNoctis** [neoclide/coc-highlight#13]
It might be useful to choose between a black or white text color depending on perceived brightness. A proposed implementation, adapted from [here](https://stackoverflow.com/a/36888120/365102) where [`Color::luminosity`](https://www.w3.org/TR/WCAG20/#relativeluminancedef) returns human-perceived luminosity:

```typescript
function getTextColor(bgColor: Color): Color {
  return new Color(bgColor.luminosity() > 0.5 ? 'black' : 'white')
}
```

For instance, in this image, the `#343a40` is hard to read:

![](https://user-images.githubusercontent.com/251450/48705891-75e27f80-ec35-11e8-91ac-ee684b937e8c.png)

**Comment by chemzqm** [comment]
Fixed on master of coc.nvim.

<img width="480" alt="Screen Shot 2019-07-01 at 9 11 33 AM" src="https://user-images.githubusercontent.com/251450/60405074-979ae080-9be0-11e9-8039-b9a48fd8b5ad.png">
