### ISSUE TITLE
Highlighting is slow

### ISSUE THREAD

**Issue by steven-lang** [neoclide/coc-highlight#16]
The highlighting seems to be really slow. Even for small files, it takes between 0.5 and 1.0 seconds.

Any chance for improvements or are you just passing the buffer to the highlight server which is the bottleneck here?

**Comment by chemzqm** [comment]
need sometime to start the server.

**Comment by yangxuanx** [comment]
我也是同样的问题，显示高亮很慢，node 12.10.0

**Comment by MeisterTea** [comment]
> Need sometime to start the server.
> Could slow on buffer create, try use minimal vimrc.

It's the same with a clean vimrc. The server takes way too much time to use this instead of something like [ap/vim-css-color](https://github.com/ap/vim-css-color)

Is there any improvement possible ?

**Comment by newbeenew** [comment]
slow after creation.  [profile.log](https://github.com/neoclide/coc-highlight/files/5274842/profile.log)

**Comment by chemzqm** [comment]
> slow after creation. [profile.log](https://github.com/neoclide/coc-highlight/files/5274842/profile.log)
> ![image](https://user-images.githubusercontent.com/8499053/94127137-200f3c00-fe8b-11ea-9eca-716c972af478.png)

It's not caused by coc.nvim

**Comment by newbeenew** [comment]
> > slow after creation. [profile.log](https://github.com/neoclide/coc-highlight/files/5274842/profile.log)
> > ![image](https://user-images.githubusercontent.com/8499053/94127137-200f3c00-fe8b-11ea-9eca-716c972af478.png)
> 
> It's not caused by coc.nvim

sorry...

**Comment by chemzqm** [comment]
From 2.0.0 coc-highlight switched to worker threads and calculate color highlights for changed lines only.
