### ISSUE TITLE
Do not highlight HTML entities

### ISSUE THREAD

**Issue by kkoomen** [neoclide/coc-highlight#18]
The current highlighting for colors should not highlight the color when prefixed with the `&` character. I suggest to add a look-around [here](https://github.com/neoclide/coc-highlight/blob/master/server/matchers.ts#L6) by optimizing the regex to:

```typescript
const colorHex = /(?<=\W|&|^)((?:#)([a-f0-9]{6}([a-f0-9]{2})?|[a-f0-9]{3}([a-f0-9]{1})?))\b/gi
```

(The above adds `&` to `(?<=\W|^)`). See [regex101](https://regex101.com/r/kV55Or/2) for working demo.

**Screenshot**
<img width="1082" alt="Screenshot 2019-08-14 at 16 18 56" src="https://user-images.githubusercontent.com/10693490/63005491-43f20700-beaf-11e9-83af-8149991b4a65.png">

**Comment by kkoomen** [comment]
@chemzqm Can you merge this?

**Comment by chemzqm** [comment]
It doesn't fix the highlight.

**Comment by kkoomen** [comment]
@chemzqm Sorry, you should use this regex ([demo](https://regex101.com/r/kV55Or/4):

```javascript
const colorHex = /(?<!&|\w)((?:#)([a-f0-9]{6}([a-f0-9]{2})?|[a-f0-9]{3}([a-f0-9]{1})?))\b/;
```

**Comment by kkoomen** [comment]
I thought it already used negative-look-behind, but it didn't, so I used that. Makes more sense in this case.

**Comment by kkoomen** [comment]
@chemzqm Can you merge?
