### ISSUE TITLE
Do not work with onedark theme

### ISSUE THREAD

**Issue by dementor5** [neoclide/coc-highlight#19]
coc-highlight breaks If i add [onedark](https://github.com/joshdick/onedark.vim) theme to my .vimrc

Which highlight group it overrides? How can i fix it?

**Comment by kkoomen** [comment]
I use onedark as well. Can you provide  a screenshot of incorrect results?

**Comment by chemzqm** [comment]
It doesn't overrides your highlight groups, so could be your other plugins cause problems.
