### ISSUE TITLE
Position of highlight doesn't change with the corresponding highlighted element

### ISSUE THREAD

**Issue by cjnucette** [neoclide/coc-highlight#2]
Let's say you have the following:
```js 
color='red';
```
The word 'red' is hightlighted as it is supposed to be, but if some space or content is added that moves the word 'red' then the highlight remains in the original place.

![screenshot from 2019-01-07 09-16-16](https://user-images.githubusercontent.com/2278326/50770237-f6e4ed00-125c-11e9-8da4-29d65a7813b5.png)

**Comment by chemzqm** [comment]
The highlight is designed to update on normal mode only for performance reason, so it's feature.
