### ISSUE TITLE
Disable highlighting in specific `hi` groups

### ISSUE THREAD

**Issue by JeanMertz** [neoclide/coc-highlight#20]
I like the highlighting this plugin provides, but it is a bit distracting when scrolling through code comments and having the comment words highlighted.

One generic way to solve this would be to make it possible to disable highlighting within specific `highlight` groups. This way I could disable the plugin for the `Comment` group and have the best of both worlds.

I'm not sure if this is at all feasible, but I figured I would ask.

**Comment by chemzqm** [comment]
There is no API to get all highlight groups of current buffer, but only API from location which would be too slow for remote plugin, so you need send feature request to vim.
