### ISSUE TITLE
Highlight current color code only

### ISSUE THREAD

**Issue by monkoose** [neoclide/coc-highlight#22]
Is there a possibility to implement feature similar to `highlight current symbol` to show color of the current colorcode only on CursorHold or keys pressed?

**Comment by chemzqm** [comment]
You mean highlight colors on CursorHold only?

**Comment by monkoose** [comment]
More like highlight ONLY color code under the cursor on CursorHold, not all color codes for a buffer.

**Comment by chemzqm** [comment]
I don't think it makes too much sense, but PR welcome.
