### ISSUE TITLE
Highlight only Hex/RGB, not names

### ISSUE THREAD

**Issue by garand** [neoclide/coc-highlight#23]
Is it possible to not highlight color names? I'm using a a CSS framework to configure colors and the names being highlighted is unnecessary and irrelevant in my use case.
<img width="227" alt="image" src="https://user-images.githubusercontent.com/82437/69366836-11ea0100-0c65-11ea-8018-fa04f69a996e.png">

**Comment by chemzqm** [comment]
PR welcome.
