### ISSUE TITLE
The highlight stays on the same area when switching buffer

### ISSUE THREAD

**Issue by ruanyl** [neoclide/coc-highlight#3]
the highlight is correct in this file
![image](https://user-images.githubusercontent.com/486382/51945426-68acf280-2427-11e9-9c3c-b2eed87929c2.png)
but if I switch to another buffer, it keeps at the same area
![image](https://user-images.githubusercontent.com/486382/51945479-8417fd80-2427-11e9-9391-384e68de0001.png)

**Comment by chemzqm** [comment]
It's fixed on master of coc.nvim.
