### ISSUE TITLE
Option to disable coc-highlight on large text files

### ISSUE THREAD

**Issue by crazyboycjr** [neoclide/coc-highlight#30]
I just found that if I open a text file of several MBs, the coc-highlight would be slow to do the highlighting work. It may take ~1s to react to the vim motion. If you are using Linux, you can test with the following commands.
```
$ du -sch vim /usr/lib/modules/`uname -r`/modules.alias
1.5M	/usr/lib/modules/5.6.15-arch1-1/modules.alias
1.5M	total
$ vim /usr/lib/modules/`uname -r`/modules.alias
```

**Comment by chemzqm** [comment]
`:h b:coc_enabled`

**Comment by crazyboycjr** [comment]
Hi @chemzqm, "coc.preferences.maxFileSize" seems to disable the entire coc, which is not expected. Maybe we need an option to just disable the highlight plugin on a large file.

**Comment by chemzqm** [comment]
You don't need that, the performance was improved

**Comment by chemzqm** [comment]
You can use `:CocCommand document.toggleColors`

**Comment by crazyboycjr** [comment]
Looks great! Thanks!
