### ISSUE TITLE
No highlight on vim files

### ISSUE THREAD

**Issue by Moshem123** [neoclide/coc-highlight#38]
When [coc-vimlsp](https://github.com/iamcco/coc-vimlsp) is installed, there's no highlighting of symbols in any way.
Only by removing this extension, or setting a different filetype (`:setf text`), it highlights symbols.
How can I fix it?
Thanks.

**Comment by chemzqm** [comment]
Can't reproduce

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by Moshem123** [comment]
@chemzqm 
According to this:
https://github.com/neoclide/coc-highlight/blob/master/Readme.md#features
This plugin should highlight `when no color provider exists from language server`, so what does it have to do with coc-vimlsp?

**Comment by chemzqm** [comment]
coc-vimlsp provide document highlight which have higher priority

**Comment by Moshem123** [comment]
@chemzqm  good point. does coc-highlight provides an option to change its priority over the lang server's highlight?

**Comment by chemzqm** [comment]
No, your language server should understand your code better than coc-highlight.

**Comment by stevensonmt** [comment]
I don't have a vim language server running and I'm not getting any color highlighing on .vim files. How do I troubleshoot this?

**Comment by chemzqm** [comment]
checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
