### ISSUE TITLE
Highlight more than just one symbol/word like in VS Code

### ISSUE THREAD

**Issue by void-m4110c** [neoclide/coc-highlight#39]
In VSCode you can select any text and all occurrences are highlighted, not just one symbol/word.
For example if I select this whole string in visual mode:
```javascript
document.querySelector('.message').textContent
```
only the word under the cursor will be highlighted (i.e. max one of the four words), but not the whole string.

Is it possible to implement this behaviour? It helps when refactoring, because it shows you duplicate code.

Thanks

**Comment by chemzqm** [comment]
Use vim's built in search

**Comment by void-m4110c** [comment]
It's not the same. What a stupid answer.

**Comment by chemzqm** [comment]
Out of scope, you can implement that by simple vim function.

**Comment by nyngwang** [comment]
> It's not the same. What a stupid answer. We can auto-highlight one word but can not one WORD? Or a visual selection?

So why you don't like the built in `/` in Vim? I do must of the phrase searching using `/`, it's so simple and __does the work when you need it__.

[<img src="https://user-images.githubusercontent.com/24765272/114804152-6bf7e300-9dd3-11eb-9329-065282396e14.png" width="150">](https://user-images.githubusercontent.com/24765272/114804152-6bf7e300-9dd3-11eb-9329-065282396e14.png)

[<img src="https://user-images.githubusercontent.com/24765272/114803880-dbb99e00-9dd2-11eb-9c55-291743dc8757.png" width="400">](https://user-images.githubusercontent.com/24765272/114803880-dbb99e00-9dd2-11eb-9c55-291743dc8757.png)
