### ISSUE TITLE
HELP: What does the "highlight curreny symbol" actualy does?

### ISSUE THREAD

**Issue by hrqmonteiro** [neoclide/coc-highlight#42]
>including document highlight **(highlight of current document symbol)** and colors highlight.

Hi this is just a doubt, i am using the plugin and the colors highlight is working fine

![2020-12-31_01-19](https://user-images.githubusercontent.com/17055027/103394277-3a019000-4b06-11eb-9a5c-0433a86418d5.png)

But i am not sure what the other part means, what exactly is the highlight of "current document symbol"? Could someone show me please?

**Comment by chemzqm** [comment]
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentSymbol
