### ISSUE TITLE
Change highlight color

### ISSUE THREAD

**Issue by teddyhwang** [neoclide/coc-highlight#6]
With `autocmd CursorHold * silent call CocActionAsync('highlight')`, the highlighted background color is not ideal. Is it possible to change the highlight background color as an option?

**Comment by chemzqm** [comment]
Sure, all you need is overwrite the highlight group, checkout `:h coc-highlights`

**Comment by expipiplus1** [comment]
Specifically the `CocHighlightText` group

**Comment by nbossard** [comment]
Got the same issue, finally wrote : 

```vim
" changing coc highlight color cause light grey is invisible
" BUT is overwritten by scheme so defining it in an autocmd after colorscheme
" change
autocmd ColorScheme * highlight CocHighlightText     ctermfg=LightMagenta    guifg=LightMagenta
```

**Comment by cristianUrbina** [comment]
t

> Got the same issue, finally wrote :
> 
> ```viml
> " changing coc highlight color cause light grey is invisible
> " BUT is overwritten by scheme so defining it in an autocmd after colorscheme
> " change
> autocmd ColorScheme * highlight CocHighlightText     ctermfg=LightMagenta    guifg=LightMagenta
> ```

Is there any way to set color for the background and not for the foreground?
