### ISSUE TITLE
Option to respect highlighted search over coc-highlight

### ISSUE THREAD

**Issue by teddyhwang** [neoclide/coc-highlight#7]
I'm looking for a way for coc-highlight to respect search highlights with something like the following:

```vim
autocmd CursorHold * silent call HighlightCursorWord()
autocmd CursorMoved * silent call ValidateHighlight()

function! HighlightCursorWord()
  let search = getreg('/')
  let cword = expand('<cword>')
  if match(cword, search) == -1
    call CocActionAsync('highlight')
  endif
endfunction

function! ValidateHighlight()
  let search = getreg('/')
  let cword = expand('<cword>')
  if match(cword, search) == 0
    call CocActionAsync('clearHighlight')
  endif
endfunction
```
There's currently no `coc-action` to do something like `clearHighlight` so this doesn't work. Is there a better way to do this?

I've attached a video of what the problem looks like where the search highlight does not kick in until after you move off the word:

![Screen Recording 2019-04-02 at 12 27 30 AM](https://user-images.githubusercontent.com/22878/55376620-3713de80-54df-11e9-9222-17450c98f53b.gif)

**Comment by chemzqm** [comment]
I think you should just decrease `updatetime` by `set updatetime=300`.

**Comment by teddyhwang** [comment]
My current setting is `set updatetime=100`

The problem is that `CocActionAsync('highlight')` will always trump the search highlight color. Here's a more clear example with just `autocmd CursorHold * silent call CocActionAsync('highlight')`:

![Screen Recording 2019-04-02 at 12 52 44 AM](https://user-images.githubusercontent.com/22878/55377188-d89c2f80-54e1-11e9-9378-2e45b5530db9.gif)
