### ISSUE TITLE
Conflict with solarized

### ISSUE THREAD

**Issue by JulioJu** [neoclide/coc-highlight#8]
Solarized is a very famous colorscheme. It has its own Wikipedia page (see https://en.wikipedia.org/wiki/Solarized_(color_scheme) ), therefore compatibility with Solarized could be cool. It seems have conflict with coc-higlight. I've tested lot of options, without success.

I've tested by put Solarized in ~/.vim/color or enable it with `vim-plug` . I've also tested with https://github.com/icymind/NeoSolarized .

Could you help me please ?

Sample of a minimal vimrc :

```vim
set nocompatible
filetype plugin indent on
syntax on
set hidden

" VimPlug
call plug#begin('~/.vim/plugged')

Plug 'altercation/vim-colors-solarized'

Plug 'neoclide/coc.nvim', {
            \ 'do': { -> coc#util#install()}
            \ }



call plug#end()

" coc-highlight works if the following line is commented
colorscheme solarized

" Smaller updatetime for CursorHold & CursorHoldI
set updatetime=300

" Following doesn't work
autocmd CursorHold * silent call CocActionAsync('highlight')


" Following doesn't work
highlight CocErrorHighlight ctermfg=Red  guifg=#ff0000
highlight CocWarningHighlight ctermfg=Red  guifg=#ff0000
highlight CocInfoHighlight ctermfg=Red  guifg=#ff0000
highlight CocHintHighlight ctermfg=Red  guifg=#ff0000
```

**Comment by chemzqm** [comment]
You should change `CocHighlightText`

**Comment by JulioJu** [comment]
@chemzqm  thanks for your answer, but add in the vimrc
```vim
highlight CocHighlightText  guibg=#111111 ctermbg=223
```

doesn't change anything !

**Comment by chemzqm** [comment]
Add `set updatetime=300` for CursorHold trigger.

**Comment by JulioJu** [comment]
Thanks for your answer, but as I've said in my first comment, I've already tested with `set updatetime=300`  .

As I've said in my first comment, under the vimrc example, the problem is when we use `colorscheme solarized`. All work well without this. I've already noticed you tell to put on top of highlight customization. 

Is a problem because Solarized is a very very famous colorscheme, that have even it's own Wikipedia article !

**Comment by chemzqm** [comment]
I can't reproduce, it works as expected for me.

**Comment by JulioJu** [comment]
I found a solution on the web. 

I not the only one to have bug with the Solarized colorscheme. Don't know exactly why sometimes Solarized doesn't let customization in ~/.vimrc. It seems caused by the order of initialization. Why the order change? Don't know, but I've found a workaround.  

To tweak colors, simply use something like the following:

`autocmd VimEnter` hooks always trigger loading of highlight customization after the load of Solarized colorscheme. Therefore, all work fine thanks this.

```vim
        function! CocNvimHighlight()
            highlight CocErrorHighlight ctermfg=Red  guifg=#ff0000
            highlight CocWarningHighlight ctermfg=Red  guifg=#ff0000
            highlight CocInfoHighlight ctermfg=Red  guifg=#ff0000
            highlight CocHintHighlight ctermfg=Red  guifg=#ff0000
            highlight CocErrorLine ctermfg=Red  guifg=#ff0000
            highlight CocWarningLine ctermfg=Red  guifg=#ff0000
            highlight CocInfoLine ctermfg=Red  guifg=#ff0000
            highlight CocHintLine ctermfg=Red  guifg=#ff0000

            highlight CocHighlightText  guibg=#111111 ctermbg=223
	endfunction

        autocmd VimEnter function CocNvimHighlight()
```

There is an other solution described in the official documentation `:help colorscheme`. @chemzqm we could deduce of this documentation that simply customize highlights in ~/init.nvim could not always work, like for me and another friend.   

```
			To customize a colorscheme use another name, e.g.
			"~/.vim/colors/mine.vim", and use `:runtime` to load
			the original colorscheme: >
```

@ readers . If you have the same problem as me, do not hesitate to tell us. As it, maybe if lot of people has this issue we could ask to add this tip in the README.
